# Generated by Django 3.2.18 on 2023-04-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_public',
        ),
    ]
